apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "lockbox-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.server.service.ports }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  selector:
    {{- include "lockbox.serviceSelectorLabels" . | nindent 4 }}