[workspace.package]
version = "0.1.1"
edition = "2024"
description = "API key authentication service for Rest APIs"
repository = "https://github.com/wizrds/lockbox"
license = "ISC"
readme = "README.md"

[workspace]
resolver = "2"
members = [
    "lockbox-macros",
    "lockbox-migrations",
    "lockbox-core",
    "lockbox-api",
    "lockbox",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_norway = { version = "0.9" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
async-trait = { version = "0.1" }
futures = { version = "0.3" }
thiserror = { version = "2.0" }
anyhow = { version = "1.0" }
validator = { version = "0.20", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
log = { version = "0.4" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }
tracing-opentelemetry = { version = "0.32" }
opentelemetry = { version = "0.31" }
opentelemetry-otlp = { version = "0.31" }
rustls = { version = "0.23", features = ["aws_lc_rs"] }
axum = { version = "0.8", features = ["tracing"] }
axum-server = { version = "0.8", features = ["tls-rustls"] }
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls", "macros", "mock", "with-json", "with-uuid", "sqlite-use-returning-for-3_35"] }
sea-orm-migration = "1.1"
uuid = { version = "1", features = ["v4", "fast-rng", "zerocopy", "serde"] }
jobq = { git = "https://github.com/wizrds/jobq-rs.git", tag = "0.1.0", version = "0.1.0" }

criterion = { version = "0.8", features = ["html_reports"] }